#Player events
voidtp: true

# World events
noweather: true
nofade: true
noliquidflow: true

# Joins
clearchatonjoin: true
joinspawn: true

# Plugin language/formatting
messages:
  join: "&2+&8{PLAYER}"
  quit: "&4-&8{PLAYER}"
  death: "&7{PLAYER} died."
  spawntp: "&aTeleported to spawn."
  voidtp: "&aYou fell into the void, so we moved you to spawn."
  cmdnoperms: "&cYou do not have permission to use this command!"
  motd:
    - This is line one of the MOTD
    - This is line two, isn't that neat?
    - '&eThis is a yellow line with some &agreen text &eto spice things up.'
    - This is the last line in the default message, it's very long like a giraffe's neck. (You can have more than 4 lines btw.)

# Everything below here is for internal use, do not hand edit unless you know what you're doing!
spawndata:
  pitch: 0
  yaw: 0
