main: io.github.thecalcium.calhub.CalHub
name: CalHub
version: ${version}
author: Calcium
website: https://calcium.pw/

commands:
  setspawn:
    description: Sets the world spawn to the issuer's current location
    usage: /<command>
  spawn:
    description: Teleports the user the world's spawn point
    usage: /<command>
  motd:
    description: Displays the server's MOTD
    usage: /<command>
permissions:
  calhub.motd:
    description: Allows viewing of the MOTD on join, and use of the /motd command
    default: true
  calhub.spawn:
    description: Allows the use of the /spawn command
    default: true
